### ISSUE TITLE
你好，我复制了你的项目，但是有个地方一直运行失败

### ISSUE THREAD

**Issue by Shura23** [REIJI007/Adblock-Rule-Collection#5]
我只修改了广告过滤规则，去掉了一些DNS过滤器
![image](https://github.com/user-attachments/assets/4423479d-92e9-4c22-a66a-a75700e2dc92)

**Comment by Shura23** [comment]
我i现在只能把这个工作流关了

**Comment by REIJI007** [comment]
secret没设置正确，我使用了自己的名为TOKEN的自定义secret，把他改回成默认的即可
```GITHUB_TOKEN: ${{ secrets.TOKEN }}```全部替换回```GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}```

**Comment by Shura23** [comment]
> secret没设置正确，我使用了自己的名为TOKEN的自定义secret，改回成默认的即可 `GITHUB_TOKEN: ${{ secrets.TOKEN }}`全部替换回`GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`

多谢，问题已经解决了
