### ISSUE TITLE
大佬，是否能提供一个去除无效域名的功能

### ISSUE THREAD

**Issue by Shura23** [REIJI007/Adblock-Rule-Collection#8]
https://github.com/AdguardTeam/DeadDomainsLinter
这是一个用于去除DNS过滤器中无效的死亡域名的工具，是否可以并入你的项目中？

**Comment by REIJI007** [comment]
要验证DNS域名保活需要发起DNS请求，对于一百多万条域名这样大规模的DNS请求势必极大拖慢python脚本的执行，占用大量的计算机资源，我认为这不必要也不可取

**Comment by Shura23** [comment]
> 要验证DNS域名保活需要发起DNS请求，对于一百多万条域名这样大规模的DNS请求势必极大拖慢python脚本的执行，占用大量的计算机资源，我认为这不必要也不可取

我觉得可以有这个功能，然后默认关闭，需要的人开启。去除无效域名后，规则会更少，使用adguard Home订阅规则，adguardHome消耗的资源也就会更少。
